using AlSsareea.CustomerApp.Core;

namespace AlSsareea.CustomerApp;

public sealed class ProductDetailsPage : RemotePage<ProductViewModel>, IQueryAttributable
{
    private readonly HorizontalStackLayout media = new() { Spacing = 8 }; private readonly VerticalStackLayout configuration = new() { Spacing = 12 }; private readonly Label price = new() { FontSize = 20 };
    public ProductDetailsPage() : base("Product")
    {
        var name = new Label { FontSize = 28, FontAttributes = FontAttributes.Bold }; name.SetBinding(Label.TextProperty, "Product.Text.Name"); var description = new Label(); description.SetBinding(Label.TextProperty, "Product.Text.Description"); var quantity = new Stepper { Minimum = 1, Maximum = 99, Increment = 1 }; quantity.SetBinding(Stepper.ValueProperty, nameof(ProductViewModel.Quantity)); var note = new Editor { Placeholder = T("CustomerNote"), AutoSize = EditorAutoSizeOption.TextChanges, MaximumHeightRequest = 120 }; note.SetBinding(Editor.TextProperty, nameof(ProductViewModel.CustomerNote)); var selectionError = new Label { TextColor = Colors.Firebrick }; selectionError.SetBinding(Label.TextProperty, nameof(ProductViewModel.SelectionError));
        var layout = new VerticalStackLayout { Padding = 20, Spacing = 12, Children = { new ScrollView { Orientation = ScrollOrientation.Horizontal, Content = media }, name, description, price, configuration, selectionError, new Label { Text = T("Quantity") }, quantity, note, Action(T("AddToCart"), ViewModel.AddToCartAsync) } }; AddState(layout); Content = new ScrollView { Content = layout }; ViewModel.PropertyChanged += (_, args) => { if (args.PropertyName is nameof(ProductViewModel.Product) or nameof(ProductViewModel.Price) or nameof(ProductViewModel.SelectedOptions) or nameof(ProductViewModel.SelectedVariantId)) Render(); };
    }
    public async void ApplyQueryAttributes(IDictionary<string, object> query) { if (PageQueries.GuidValue(query, "merchantId", out Guid merchant) && PageQueries.GuidValue(query, "productId", out Guid product)) { await ViewModel.LoadAsync(merchant, product); Render(); } }
    private void Render()
    {
        price.Text = ViewModel.Price is null ? string.Empty : F("PriceWithCurrencyFormat", ViewModel.Price.TotalPriceMinor, ViewModel.Price.Currency); media.Clear();
        if (ViewModel.Media.Count == 0) media.Add(new Label { Text = T("NoProductMedia"), HeightRequest = 180, WidthRequest = 280, HorizontalTextAlignment = TextAlignment.Center, VerticalTextAlignment = TextAlignment.Center });
        foreach (CustomerProductMediaResponse item in ViewModel.Media) { var image = new Image { Source = new UriImageSource { Uri = new Uri(item.Url), CachingEnabled = true, CacheValidity = TimeSpan.FromDays(1) }, Aspect = Aspect.AspectFill, HeightRequest = 220, WidthRequest = 320 }; SemanticProperties.SetDescription(image, item.AltText ?? ViewModel.Product?.Text.Name ?? T("ProductImage")); media.Add(new Grid { HeightRequest = 220, WidthRequest = 320, Children = { new Label { Text = T("NoProductMedia"), HorizontalTextAlignment = TextAlignment.Center, VerticalTextAlignment = TextAlignment.Center }, image } }); }
        configuration.Clear();
        if (ViewModel.Variants.Count > 0) { configuration.Add(new Label { Text = T("Variants"), FontSize = 20, FontAttributes = FontAttributes.Bold }); foreach (CustomerProductVariantResponse variant in ViewModel.Variants) { string marker = ViewModel.IsSelected(variant) ? "✓ " : string.Empty; configuration.Add(Action(marker + F("ChoicePriceFormat", variant.Text.Name, variant.PriceAdjustmentMinor), async () => { await ViewModel.SelectVariantAsync(variant); Render(); }, variant.IsAvailable)); } }
        if (ViewModel.OptionGroups.Count > 0) configuration.Add(new Label { Text = T("Options"), FontSize = 20, FontAttributes = FontAttributes.Bold });
        foreach (CustomerProductOptionGroupResponse group in ViewModel.OptionGroups) { configuration.Add(new Label { Text = F("OptionGroupFormat", group.Text.Name, T(group.IsRequired ? "Required" : "Optional"), group.MinSelections, group.MaxSelections), FontAttributes = FontAttributes.Bold }); foreach (CustomerProductOptionResponse option in group.Options) { string marker = ViewModel.IsSelected(group, option) ? "✓ " : string.Empty; configuration.Add(Action(marker + F("ChoicePriceFormat", option.Text.Name, option.PriceAdjustmentMinor), async () => { await ViewModel.ToggleOptionAsync(group, option); Render(); }, option.IsAvailable)); } }
    }
}

public sealed class CartPage : RemotePage<CartViewModel>
{
    private readonly VerticalStackLayout items = new() { Spacing = 8 }; private readonly Entry coupon;
    public CartPage() : base("Cart")
    {
        coupon = new Entry { Placeholder = T("CouponCode"), MinimumHeightRequest = 48 }; var total = new Label { FontSize = 20, FontAttributes = FontAttributes.Bold }; total.SetBinding(Label.TextProperty, "Summary.GrandTotalMinor", stringFormat: T("AuthoritativeTotalFormat")); var layout = new VerticalStackLayout { Padding = 18, Spacing = 10, Children = { new Label { Text = T("YourCart"), FontSize = 28, FontAttributes = FontAttributes.Bold }, items, total, coupon, Action(T("ApplyCoupon"), () => ViewModel.ApplyCouponAsync(coupon.Text ?? string.Empty)), Action(T("RemoveCoupon"), ViewModel.RemoveCouponAsync), Action(T("ClearCart"), ViewModel.ClearAsync), Action(T("Checkout"), ViewModel.CheckoutAsync) } }; AddState(layout); Content = new ScrollView { Content = layout }; ViewModel.PropertyChanged += (_, args) => { if (args.PropertyName is nameof(CartViewModel.Items) or nameof(CartViewModel.Summary)) Render(); };
    }
    protected override async void OnAppearing() { base.OnAppearing(); await ViewModel.LoadAsync(true); Render(); }
    private void Render() { items.Clear(); foreach (CartItemResponse item in ViewModel.Items) { CartCheckoutItemResponse? summary = ViewModel.Summary?.Items.FirstOrDefault(value => value.CartItemId == item.Id); string label = summary?.ProductName ?? T("Product"); var row = new VerticalStackLayout { Children = { new Label { Text = F("CartItemFormat", label, item.Quantity), FontAttributes = FontAttributes.Bold } } }; foreach (CartCheckoutOptionResponse option in summary?.Options ?? []) row.Add(new Label { Text = F("CartOptionFormat", option.OptionGroupName, option.OptionName) }); row.Add(new HorizontalStackLayout { Spacing = 6, Children = { Action("−", () => item.Quantity <= 1 ? ViewModel.RemoveAsync(item) : ViewModel.ChangeQuantityAsync(item, item.Quantity - 1)), Action("+", () => ViewModel.ChangeQuantityAsync(item, item.Quantity + 1)), Action(T("Remove"), () => ViewModel.RemoveAsync(item)) } }); items.Add(new Border { Padding = 12, Content = row }); } }
}

public sealed class AddressesPage : RemotePage<AddressesViewModel>
{
    private readonly VerticalStackLayout items = new() { Spacing = 8 }; private readonly VerticalStackLayout suggestions = new() { Spacing = 6 }; private readonly Entry query; private readonly Entry label; private readonly Entry city; private readonly Entry area; private readonly Entry street; private readonly Entry building; private readonly Entry floor; private readonly Entry apartment; private readonly Editor instructions; private readonly Switch isDefault = new(); private AddressResponse? editing; private GeocodingResult? selectedLocation;
    public AddressesPage() : base("Addresses")
    {
        query = Entry("EnterAddress"); label = Entry("AddressLabel"); city = Entry("City"); area = Entry("Area"); street = Entry("Street"); building = Entry("BuildingNumber"); floor = Entry("Floor"); apartment = Entry("Apartment"); instructions = new Editor { Placeholder = T("DeliveryInstructions"), AutoSize = EditorAutoSizeOption.TextChanges };
        var layout = new VerticalStackLayout { Padding = 18, Spacing = 10, Children = { label, city, area, street, building, floor, apartment, instructions, new HorizontalStackLayout { Children = { new Label { Text = T("DefaultAddress"), VerticalTextAlignment = TextAlignment.Center }, isDefault } }, query, Action(T("FindAddress"), SearchAsync), Action(T("UseCurrentLocation"), UseCurrentLocationAsync), suggestions, Action(T("SaveAddress"), SaveAsync), Action(T("CancelEdit"), () => { ResetForm(); return Task.CompletedTask; }), new Label { Text = T("SavedAddresses"), FontSize = 20, FontAttributes = FontAttributes.Bold }, items } }; AddState(layout); Content = new ScrollView { Content = layout };
    }
    protected override async void OnAppearing() { base.OnAppearing(); await ViewModel.LoadAsync(); RenderAddresses(); }
    private Entry Entry(string key) => new() { Placeholder = T(key), MinimumHeightRequest = 48 };
    private async Task SearchAsync() { await ViewModel.SearchAddressAsync(query.Text ?? string.Empty); RenderSuggestions(); }
    private void RenderAddresses() { items.Clear(); foreach (AddressResponse address in ViewModel.Items) { var row = new VerticalStackLayout { Children = { new Label { Text = F("AddressFormat", address.Label, address.Street, address.City, address.IsDefault ? T("DefaultSuffix") : string.Empty) }, Action(T("Edit"), () => { BeginEdit(address); return Task.CompletedTask; }), Action(T("SetDefault"), async () => { await ViewModel.SetDefaultAsync(address); RenderAddresses(); }), Action(T("Delete"), async () => { await ViewModel.DeleteAsync(address); RenderAddresses(); }) } }; items.Add(new Border { Padding = 12, Content = row }); } }
    private void RenderSuggestions() { suggestions.Clear(); foreach (GeocodingResult result in ViewModel.Suggestions) suggestions.Add(Action(result.FormattedAddress, () => { selectedLocation = result; query.Text = result.FormattedAddress; suggestions.Clear(); return Task.CompletedTask; })); }
    private void BeginEdit(AddressResponse address) { editing = address; selectedLocation = address.Latitude.HasValue && address.Longitude.HasValue ? new(query.Text ?? string.Empty, address.Latitude.Value, address.Longitude.Value, address.PlaceId) : null; label.Text = address.Label; city.Text = address.City; area.Text = address.Area; street.Text = address.Street; building.Text = address.BuildingNumber; floor.Text = address.Floor; apartment.Text = address.Apartment; instructions.Text = address.DeliveryInstructions; isDefault.IsToggled = address.IsDefault; }
    private async Task SaveAsync() { double? latitude = selectedLocation?.Latitude ?? editing?.Latitude; double? longitude = selectedLocation?.Longitude ?? editing?.Longitude; var request = new AddressRequest(label.Text ?? string.Empty, editing?.AddressType ?? 1, city.Text ?? string.Empty, Empty(area.Text), street.Text ?? string.Empty, Empty(building.Text), Empty(floor.Text), Empty(apartment.Text), editing?.PostalCode, selectedLocation?.PlaceId ?? editing?.PlaceId, latitude, longitude, Empty(instructions.Text), isDefault.IsToggled, editing?.ConcurrencyStamp); if (await ViewModel.SaveAsync(editing, request)) { ResetForm(); RenderAddresses(); } }
    private async Task UseCurrentLocationAsync() { Location? location = await Geolocation.Default.GetLocationAsync(new GeolocationRequest(GeolocationAccuracy.Medium, TimeSpan.FromSeconds(15))); if (location is null) return; selectedLocation = await ViewModel.ReverseAsync(location.Latitude, location.Longitude); if (selectedLocation is not null) query.Text = selectedLocation.FormattedAddress; }
    private void ResetForm() { editing = null; selectedLocation = null; foreach (InputView input in new InputView[] { query, label, city, area, street, building, floor, apartment, instructions }) input.Text = string.Empty; isDefault.IsToggled = false; suggestions.Clear(); }
    private static string? Empty(string? value) => string.IsNullOrWhiteSpace(value) ? null : value.Trim();
}

public sealed class CheckoutPage : RemotePage<CheckoutViewModel>, IQueryAttributable
{
    public CheckoutPage() : base("Checkout") { var addresses = new Picker { Title = T("DeliveryAddress"), MinimumHeightRequest = 48 }; addresses.SetBinding(Picker.ItemsSourceProperty, nameof(CheckoutViewModel.Addresses)); addresses.ItemDisplayBinding = new Binding(nameof(AddressResponse.Label)); addresses.SetBinding(Picker.SelectedItemProperty, nameof(CheckoutViewModel.SelectedAddress)); var total = new Label { FontSize = 22, FontAttributes = FontAttributes.Bold }; total.SetBinding(Label.TextProperty, "Summary.GrandTotalMinor", stringFormat: T("TotalFormat")); var layout = new VerticalStackLayout { Padding = 20, Spacing = 12, Children = { addresses, total, new Label { Text = T("NonElectronicPayment") }, Action(T("PlaceOrder"), ViewModel.SubmitAsync) } }; AddState(layout); Content = new ScrollView { Content = layout }; }
    public async void ApplyQueryAttributes(IDictionary<string, object> query) { if (PageQueries.GuidValue(query, "cartId", out Guid id)) await ViewModel.LoadAsync(id); }
}
