using AlSsareea.CustomerApp.Core;

namespace AlSsareea.CustomerApp.UnitTests;

public sealed class ProfileTests
{
    [Fact] public async Task Profile_load_and_update_use_backend_concurrency() { var customer = new CustomerStub(); var vm = Create(customer, new AccountStub(), new SessionStub(), out _); await vm.LoadAsync(); Guid stamp = vm.Customer!.ConcurrencyStamp; await vm.UpdateAsync(" New ", " Name ", null); Assert.Equal(stamp, customer.UpdateRequest!.ConcurrencyStamp); Assert.Equal("New", customer.UpdateRequest.FirstName); }
    [Fact] public async Task Logout_success_clears_local_session_and_routes_login() { var session = new SessionStub(); var vm = Create(new CustomerStub(), new AccountStub(), session, out TestNavigation navigation); await vm.LogoutAsync(); Assert.True(session.Cleared); Assert.Equal(AppRoutes.Login, Assert.Single(navigation.Visits).Route); }
    [Fact] public async Task Backend_logout_failure_still_clears_local_session() { var session = new SessionStub(); var vm = Create(new CustomerStub(), new AccountStub { Fail = true }, session, out TestNavigation navigation); await vm.LogoutAsync(); Assert.True(session.Cleared); Assert.Equal(AppRoutes.Login, Assert.Single(navigation.Visits).Route); }
    private static ProfileViewModel Create(CustomerStub customer, AccountStub account, SessionStub session, out TestNavigation navigation) { navigation = new(); return new(customer, account, session, new UserStateResetter([]), new TestPreferences(), new TestText(), new OnlineConnectivity(), navigation); }
    private sealed class CustomerStub : ICustomerApi
    {
        private CustomerResponse value = new(Guid.NewGuid(), "First", "Last", "First Last", null, 1, DateTime.UtcNow, DateTime.UtcNow, Guid.NewGuid()); public UpdateCustomerRequest? UpdateRequest { get; private set; }
        public Task<CustomerResponse> GetAsync(CancellationToken ct) => Task.FromResult(value); public Task<CustomerResponse> UpdateAsync(UpdateCustomerRequest request, CancellationToken ct) { UpdateRequest = request; value = value with { FirstName = request.FirstName, LastName = request.LastName, DisplayName = $"{request.FirstName} {request.LastName}", ConcurrencyStamp = Guid.NewGuid() }; return Task.FromResult(value); }
        public Task<IReadOnlyList<AddressResponse>> AddressesAsync(CancellationToken ct) => throw new NotSupportedException(); public Task<AddressResponse> AddAddressAsync(AddressRequest request, CancellationToken ct) => throw new NotSupportedException(); public Task<AddressResponse> UpdateAddressAsync(Guid id, AddressRequest request, CancellationToken ct) => throw new NotSupportedException(); public Task DeleteAddressAsync(Guid id, Guid concurrencyStamp, CancellationToken ct) => throw new NotSupportedException(); public Task<AddressResponse> SetDefaultAddressAsync(Guid id, Guid concurrencyStamp, CancellationToken ct) => throw new NotSupportedException(); public Task<CustomerPreferencesResponse> PreferencesAsync(CancellationToken ct) => throw new NotSupportedException(); public Task<CustomerPreferencesResponse> UpdatePreferencesAsync(UpdateCustomerPreferencesRequest request, CancellationToken ct) => throw new NotSupportedException();
    }
    private sealed class AccountStub : IAccountSessionApi { public bool Fail { get; init; } public Task LogoutAsync(string idempotencyKey, CancellationToken ct) => Fail ? Task.FromException(new ApiNetworkException("network", new HttpRequestException())) : Task.CompletedTask; }
    private sealed class SessionStub : ISessionManager { public bool Cleared { get; private set; } public string? AccessToken => "token"; public DateTime? AccessTokenExpiresUtc => DateTime.UtcNow.AddMinutes(1); public Guid? UserId => Guid.NewGuid(); public bool IsAuthenticated => !Cleared; public Task ClearAsync(CancellationToken ct) { Cleared = true; return Task.CompletedTask; } public Task<bool> RefreshAsync(string? failedAccessToken, CancellationToken ct) => Task.FromResult(true); public Task<bool> RestoreAsync(CancellationToken ct) => Task.FromResult(true); public Task SetAsync(TokenResponse tokens, string deviceIdentifier, CancellationToken ct) => Task.CompletedTask; }
}
