using AlSsareea.CustomerApp.Core;
namespace AlSsareea.CustomerApp.UnitTests;

public sealed class SessionManagerTests
{
    [Fact] public async Task Restore_without_session_is_unauthenticated() { var m = new SessionManager(new MemoryStorage(), new FakeAuth()); Assert.False(await m.RestoreAsync(default)); Assert.False(m.IsAuthenticated); }
    [Fact] public async Task Concurrent_unauthorized_requests_rotate_once() { var s = new MemoryStorage(); var a = new FakeAuth(); var m = new SessionManager(s, a); await m.SetAsync(FakeAuth.Token("access-1", "refresh-1"), "device", default); bool[] r = await Task.WhenAll(Enumerable.Range(0, 20).Select(_ => m.RefreshAsync("access-1", default))); Assert.All(r, Assert.True); Assert.Equal(1, a.RefreshCount); Assert.Equal("access-2", m.AccessToken); Assert.Equal("refresh-2", s.Value?.RefreshToken); }
    [Fact] public async Task Permanent_failure_clears_session() { var s = new MemoryStorage { Value = new("bad", DateTime.UtcNow.AddHours(1), "device") }; var m = new SessionManager(s, new FakeAuth { Fail = true }); Assert.False(await m.RestoreAsync(default)); Assert.Null(s.Value); Assert.Null(m.AccessToken); }
    [Fact] public async Task Restore_success_rotates_refresh_and_sets_user() { var s = new MemoryStorage { Value = new("refresh-1", DateTime.UtcNow.AddHours(1), "device") }; var m = new SessionManager(s, new FakeAuth()); Assert.True(await m.RestoreAsync(default)); Assert.Equal("refresh-2", s.Value!.RefreshToken); Assert.NotNull(m.UserId); Assert.True(m.AccessTokenExpiresUtc > DateTime.UtcNow); }
    [Fact] public async Task Expired_stored_session_is_cleared_without_refresh() { var s = new MemoryStorage { Value = new("expired", DateTime.UtcNow.AddMinutes(-1), "device") }; var a = new FakeAuth(); var m = new SessionManager(s, a); Assert.False(await m.RestoreAsync(default)); Assert.Equal(0, a.RefreshCount); Assert.Null(s.Value); }
    [Fact] public async Task Clear_removes_secure_and_memory_state() { var s = new MemoryStorage(); var m = new SessionManager(s, new FakeAuth()); await m.SetAsync(FakeAuth.Token("access", "refresh"), "device", default); await m.ClearAsync(default); Assert.Null(m.AccessToken); Assert.Null(m.AccessTokenExpiresUtc); Assert.Null(m.UserId); Assert.Null(s.Value); }
    private sealed class MemoryStorage : ISessionStorage { public StoredSession? Value { get; set; } public Task ClearAsync(CancellationToken ct) { Value = null; return Task.CompletedTask; } public Task<StoredSession?> GetAsync(CancellationToken ct) => Task.FromResult(Value); public Task SetAsync(StoredSession session, CancellationToken ct) { Value = session; return Task.CompletedTask; } }
    private sealed class FakeAuth : IAuthenticationApi { private int count; public bool Fail { get; init; } public int RefreshCount => count; public static TokenResponse Token(string a, string r) => new("Bearer", a, 900, r, DateTime.UtcNow.AddHours(1), Guid.NewGuid(), new(Guid.NewGuid(), "Customer")); public Task<TokenResponse> RefreshAsync(RefreshRequest r, CancellationToken ct) { Interlocked.Increment(ref count); if (Fail) throw new ApiException(new(401, "Unauthorized", null, "auth.refresh_token_invalid", new Dictionary<string, string[]>())); return Task.FromResult(Token("access-2", "refresh-2")); } public Task<TokenResponse> LoginAsync(LoginRequest r, CancellationToken ct) => throw new NotSupportedException(); public Task LogoutAsync(string k, CancellationToken ct) => throw new NotSupportedException(); public Task<OtpChallengeResponse> RequestOtpAsync(OtpChallengeRequest r, string k, CancellationToken ct) => throw new NotSupportedException(); public Task VerifyOtpAsync(Guid i, OtpVerifyRequest r, CancellationToken ct) => throw new NotSupportedException(); }
}
